
---
# File: install.yml - package installation tasks for `pkg` deps

- name: OS packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ os_packages }}"
  become: true
  become_user: root
  tags: installation


